### ISSUE TITLE
Center Image not showing properly

### ISSUE THREAD

**Issue by TamilRaja** [nitingohel/CustomTabCenterBig#2]
Hi 
 
  I have used your SDK. It's nice animations in tabbar controller. But i have integrated my application it's  not coming proper desing. Kindly give suggestion what i wrongly did. For your reference attached my screen. 

Yours 
![screen shot 2018-07-04 at 10 41 03 am](https://user-images.githubusercontent.com/3132231/42257930-c52ade38-7f76-11e8-8dc2-c0b0656e860b.png)

Me
![screen shot 2018-07-04 at 10 39 30 am](https://user-images.githubusercontent.com/3132231/42257898-90bc2e9a-7f76-11e8-9718-5b3dbd6594ae.png)

**Comment by nitingohel** [comment]
You can debug might you are forget something to add or our image are too small so kindly check with big size image what you use for camera

**Comment by TamilRaja** [comment]
Thanks for your response. No i have used your image only i didn't change anything. just circle colour only changed and remove border. Reaming everything yours only. Pls give me idea how to fix this issues last one day i tried ...

**Comment by TamilRaja** [comment]
HI 
  Now i fixed. Your updated pod file is not working properly. I changed pod file  'ESTabBarController-swift', '~> 2.1.0' now it's working fine. Thanks bro...
